language: python
dist: bionic
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
stages:
  - test
  - lint
  - wheels
env:
  - PATH=$HOME/.cargo/bin:$PATH
matrix:
  include:
    - python: '3.8'
      name: 'rust linters'
      install: true
      script:
        - cargo clippy || true
        - cargo fmt -- --check  || true
      stage: lint
    - python: '3.8'
      name: 'manylinux2010'
      before_install: true
      install: true
      env:
        - PYPI_USERNAME=ahoetker
      script:
        - sudo docker build -f manylinux2010.dockerfile -t mandelbrot_rs_manylinux2010:latest .
        - sudo docker run -e NO_SDIST="1" -e MANYLINUX_VERSION="2010" -e TRAVIS_TAG="$TRAVIS_TAG" -e PYPI_USERNAME="$PYPI_USERNAME" -e MATURIN_PASSWORD="$PYO3_PACK_PASSWORD" -v $PWD:/tmp/src mandelbrot_rs_manylinux2010:latest
      stage: wheels
    - python: '3.8'
      name: 'manylinux2014'
      before_install: true
      install: true
      env:
        - PYPI_USERNAME=ahoetker
      script:
        - sudo docker build -f manylinux2014.dockerfile -t mandelbrot_rs_manylinux2014:latest .
        - sudo docker run -e MANYLINUX_VERSION="2014" -e TRAVIS_TAG="$TRAVIS_TAG" -e PYPI_USERNAME="$PYPI_USERNAME" -e MATURIN_PASSWORD="$PYO3_PACK_PASSWORD" -v $PWD:/tmp/src mandelbrot_rs_manylinux2014:latest
      stage: wheels
    - python: '3.8'
      name: 'manylinux1'
      before_install: true
      install: true
      env:
        - PYPI_USERNAME=ahoetker
      script:
        - sudo docker build -f manylinux1.dockerfile -t mandelbrot_rs_manylinux1:latest .
        - sudo docker run -e NO_SDIST="1" -e MANYLINUX_VERSION="1" -e TRAVIS_TAG="$TRAVIS_TAG" -e PYPI_USERNAME="$PYPI_USERNAME" -e MATURIN_PASSWORD="$PYO3_PACK_PASSWORD" -v $PWD:/tmp/src mandelbrot_rs_manylinux1:latest
      stage: wheels
cache:
  pip: true
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target
before_cache:
  - sudo rm -R $TRAVIS_BUILD_DIR/target/wheels

before_install:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly --component clippy rustfmt

install: pip install -U tox maturin tox-pyo3 tox-travis numpy

script: tox